version: '2'
services:
  app:
    image: reto01_app
    ports:
      - "5000:5000"

  postgres:
    image: reto01_bd
    ports:
      - "5555:5432"

  proxy:
    image: reto01_nginx
    ports:
      - "80:80"