apiVersion: apps/v1
kind: Deployment
metadata:
  name: mypyapp
spec:
  selector:
      matchLabels:
        app: mypyapp
  replicas: 2
  template:
      metadata:
        labels:
            app: mypyapp
      spec:
        containers:
        - name: mypyapp
          image: reto01.azurecr.io/mypyapp:v1
          imagePullPolicy: Always
          readinessProbe:
            httpGet:
              port: 5000
              path: /
          livenessProbe:
            httpGet:
              port: 5000
              path: /
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "500m"
